CREATE TABLE ASIENTOS_CONTABLES (
    ID_ASIENTO        BIGSERIAL PRIMARY KEY,
    FECHA_CONTABLE    NUMERIC(8,0)  NOT NULL,
    NUMERO_MOVIMIENTO NUMERIC(10,0) NOT NULL,
    CUENTA_CONTABLE   NUMERIC(10,0) NOT NULL,
    TIPO_AFECTACION   CHAR(1) NOT NULL CHECK (TIPO_AFECTACION IN ('D','C')),
    VALOR             NUMERIC(11,2) NOT NULL,
    REFERENCIA        VARCHAR(20)
);
