CREATE TABLE MOVIMIENTOS (
    ID_MOVIMIENTO     BIGSERIAL PRIMARY KEY,
    NUMERO_MOVIMIENTO NUMERIC(10,0) NOT NULL,
    FECHA_MOVIMIENTO  NUMERIC(8,0)  NOT NULL,   -- AAAAMMDD
    CODIGO_SUCURSAL   VARCHAR(4)    NOT NULL,
    CODIGO_TIPO_MOV   VARCHAR(3)    NOT NULL,
    REFERENCIA        VARCHAR(20),
    VALOR             NUMERIC(11,2) NOT NULL,
    FECHA_CONTABLE    NUMERIC(8,0)  NOT NULL,   -- la que ingresa el usuario
    ESTADO_PROCESO    CHAR(1) NOT NULL DEFAULT 'P'
                      CHECK (ESTADO_PROCESO IN ('P','C','R')),   -- Pendiente / Contabilizado / Rechazado
    MOTIVO_RECHAZO    VARCHAR(30)
);
