CREATE TABLE PLAN_CUENTAS (
    CUENTA_CONTABLE NUMERIC(10, 0) PRIMARY KEY,
    DESCRIPCION VARCHAR(50) NOT NULL,
    TIPO_CUENTA CHAR(1) NOT NULL CHECK (TIPO_CUENTA IN ('A', 'P', 'I', 'G')),
    ESTADO CHAR(1) NOT NULL CHECK (ESTADO IN ('A', 'I'))
);

--create

INSERT INTO PLAN_CUENTAS
    (CUENTA_CONTABLE, DESCRIPCION, TIPO_CUENTA, ESTADO)
VALUES
    (1101010001, 'Caja General', 'A', 'A'),
    (2101010001, 'Depositos de Clientes', 'P', 'A'),
    (4101010001, 'Ingresos por Servicios', 'I', 'A');