CREATE TABLE SUCURSALES (
    CODIGO_SUCURSAL VARCHAR(4) PRIMARY KEY,
    NOMBRE_SUCURSAL VARCHAR(40) NOT NULL,
    ESTADO CHAR(1) NOT NULL CHECK (ESTADO IN ('A', 'I'))
);

-- create
INSERT INTO SUCURSALES (CODIGO_SUCURSAL, NOMBRE_SUCURSAL, ESTADO) VALUES
('0001', 'Sucursal Matriz', 'A'),
('0002', 'Sucursal Norte', 'A'),
('0003', 'Sucursal Sur', 'I');
