CREATE TABLE ASIENTOS_CONTABLES (
    ID_ASIENTO        BIGSERIAL PRIMARY KEY,
    FECHA_CONTABLE    NUMERIC(8,0)  NOT NULL,
    NUMERO_MOVIMIENTO NUMERIC(10,0) NOT NULL,
    CUENTA_CONTABLE   NUMERIC(10,0) NOT NULL,
    TIPO_AFECTACION   CHAR(1) NOT NULL CHECK (TIPO_AFECTACION IN ('D','C')),
    VALOR             NUMERIC(11,2) NOT NULL,
    REFERENCIA        VARCHAR(20)
);


CREATE TABLE MOVIMIENTOS (
    ID_MOVIMIENTO     BIGSERIAL PRIMARY KEY,
    NUMERO_MOVIMIENTO NUMERIC(10,0) NOT NULL,
    FECHA_MOVIMIENTO  NUMERIC(8,0)  NOT NULL,   -- AAAAMMDD
    CODIGO_SUCURSAL   VARCHAR(4)    NOT NULL,
    CODIGO_TIPO_MOV   VARCHAR(3)    NOT NULL,
    REFERENCIA        VARCHAR(20),
    VALOR             NUMERIC(11,2) NOT NULL,
    FECHA_CONTABLE    NUMERIC(8,0)  NOT NULL,   -- la que ingresa el usuario
    ESTADO_PROCESO    CHAR(1) NOT NULL DEFAULT 'P'
                      CHECK (ESTADO_PROCESO IN ('P','C','R')),   -- Pendiente / Contabilizado / Rechazado
    MOTIVO_RECHAZO    VARCHAR(30)
);


CREATE TABLE PLAN_CUENTAS (
    CUENTA_CONTABLE NUMERIC(10, 0) PRIMARY KEY,
    DESCRIPCION VARCHAR(50) NOT NULL,
    TIPO_CUENTA CHAR(1) NOT NULL CHECK (TIPO_CUENTA IN ('A', 'P', 'I', 'G')),
    ESTADO CHAR(1) NOT NULL CHECK (ESTADO IN ('A', 'I'))
);

--create

INSERT INTO PLAN_CUENTAS
    (CUENTA_CONTABLE, DESCRIPCION, TIPO_CUENTA, ESTADO)
VALUES
    (1101010001, 'Caja General', 'A', 'A'),
    (2101010001, 'Depositos de Clientes', 'P', 'A'),
    (4101010001, 'Ingresos por Servicios', 'I', 'A');

CREATE TABLE SUCURSALES (
    CODIGO_SUCURSAL VARCHAR(4) PRIMARY KEY,
    NOMBRE_SUCURSAL VARCHAR(40) NOT NULL,
    ESTADO CHAR(1) NOT NULL CHECK (ESTADO IN ('A', 'I'))
);

-- create
INSERT INTO SUCURSALES (CODIGO_SUCURSAL, NOMBRE_SUCURSAL, ESTADO) VALUES
('0001', 'Sucursal Matriz', 'A'),
('0002', 'Sucursal Norte', 'A'),
('0003', 'Sucursal Sur', 'I');



CREATE TABLE TIPOS_MOVIMIENTO (
    CODIGO_TIPO_MOV VARCHAR(3) PRIMARY KEY,
    DESCRIPCION VARCHAR(30) NOT NULL,
    CUENTA_DEBITO NUMERIC(10, 0) NOT NULL,
    CUENTA_CREDITO NUMERIC(10, 0) NOT NULL,
    ESTADO CHAR(1) NOT NULL CHECK (ESTADO IN ('A', 'I'))
);


-- create

INSERT INTO TIPOS_MOVIMIENTO
    (CODIGO_TIPO_MOV, DESCRIPCION, CUENTA_DEBITO, CUENTA_CREDITO, ESTADO)
VALUES
    ('001', 'Deposito en efectivo', 1101010001, 2101010001, 'A'),
    ('002', 'Retiro en efectivo', 2101010001, 1101010001, 'A'),
    ('003', 'Pago de servicio', 2101020001, 1101020001, 'I');